# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 88
proseWrap: always
tabWidth: 4
semi: true
trailingComma: "es5"
xmlWhitespaceSensitivity: "ignore"
plugins:
    - "/usr/local/lib/node_modules/@prettier/plugin-xml/src/plugin.js"
    - "/usr/local/lib/node_modules/prettier-plugin-sql/lib/index.cjs"
overrides:
    - files: "*.xml"
      options:
          parser: "xml"
    - files: "*.sql"
      options:
          parser: "sql"
          language: "postgresql"
          keywordCase: "upper"
