version: "3.5"
services:
    db:
        image: postgres:14
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data
        container_name: ams_db
        ports:
        # если нужно запустить несколько разных проектов, то порт нужно менять. Порт, который первый указан, 
        # это порт на хосте, а второй - порт в контейнере
        # нужно менять тот, что на хосте
        # например, если у вас есть еще один проект, то порт можно поменять на 5433:5432
        # этот же порт нужно будет указать в настройках odoo
            - "5432:5432"
        volumes:
            - ../conf/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
            - ../conf/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - odoo-pg-data:/var/lib/postgresql/data
        command: |
            postgres
            -c 'config_file=/etc/postgresql/postgresql.conf'
            -c 'hba_file=/etc/postgresql/pg_hba.conf'
            -c 'data_directory=/var/lib/postgresql/data'

volumes:
    odoo-pg-data:
